# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "word_wrap", "~> 1.0"

gem "tty-prompt", "~> 0.21.0"

gem "colorize", "~> 0.8.1"

gem "geocoder", "~> 1.6"

gem "nokogiri", "~> 1.12"

gem "httparty", "~> 0.18.0"
